services:
  aiohttp:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/aio-libs/aiohttp
        APP_VERSION: 7f0532c1df1915e4367ff4af25cd8453d2df9fc0
      context: ./images/origins/aiohttp
    x-props:
      role: origin
  apache_httpd:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: 533c0167bbf90f0beced9f96bdff97894aeb41a7
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: 016f56a0357b53821aec7f59302cd4063f1e4eda
        CONFIG_FILE: server.conf
        START_SCRIPT: start.sh
      context: ./images/origins/apache_httpd
    x-props:
      role: origin
  apache_httpd_proxy:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: 533c0167bbf90f0beced9f96bdff97894aeb41a7
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: 016f56a0357b53821aec7f59302cd4063f1e4eda
        CONFIG_FILE: proxy.conf
        START_SCRIPT: start_proxy.sh
      context: ./images/origins/apache_httpd
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  apache_tomcat:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/apache/tomcat
        APP_VERSION: 344692489fb6bbaa69ba701cccf1c76f16e814e2
      context: ./images/origins/apache_tomcat
    x-props:
      role: origin
  apache_traffic_server:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/apache/trafficserver
        APP_VERSION: 4e4be01a6b3c378386edfa72d94f6ca468fa1acb
        CACHE_CONFIG: cache.config
        RECORDS_YAML: records.yaml
        REMAP_CONFIG: remap.config
      context: ./images/transducers/apache_traffic_server
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  aws_c_http:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/awslabs/aws-c-http
        APP_VERSION: 8aefd899fc3210bfd0e3fd414011a3cb708bf6e4
        AWS_C_CAL_BRANCH: main
        AWS_C_CAL_REPO: https://github.com/awslabs/aws-c-cal
        AWS_C_CAL_VERSION: 9edd8eac2b21ca6a04535b91d60d361c2f1bb60f
        AWS_C_COMMON_BRANCH: main
        AWS_C_COMMON_REPO: https://github.com/awslabs/aws-c-common
        AWS_C_COMMON_VERSION: d3b926fd87e6c37887ae12bb2253550334e7445a
        AWS_C_COMPRESSION_BRANCH: main
        AWS_C_COMPRESSION_REPO: https://github.com/awslabs/aws-c-compression
        AWS_C_COMPRESSION_VERSION: d8264e64f698341eb03039b96b4f44702a9b3f83
        AWS_C_IO_BRANCH: main
        AWS_C_IO_REPO: https://github.com/awslabs/aws-c-io
        AWS_C_IO_VERSION: 8234042f8a5a3ba40df5212c4c9ee4b48529825b
        AWS_LC_BRANCH: main
        AWS_LC_REPO: https://github.com/aws/aws-lc
        AWS_LC_VERSION: 22e6d590984d7b62c90b0cb4e0151bdb96eb0441
        S2N_TLS_BRANCH: main
        S2N_TLS_REPO: https://github.com/aws/s2n-tls
        S2N_TLS_VERSION: 497370aa5bb18632a5d35a89395d91df3c5e87d0
      context: ./images/origins/aws_c_http
    x-props:
      role: origin
  busybox:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://git.busybox.net/busybox
        APP_VERSION: 74ac096e895acd6b02976bb010e9b3511234e899
      context: ./images/origins/busybox
    x-props:
      role: origin
  cpp_httplib:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/yhirose/cpp-httplib
        APP_VERSION: 008e107d0fcddee7cb96dc5ad3c3189fd090e40a
      context: ./images/origins/cpp_httplib
    x-props:
      role: origin
  eclipse_grizzly:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/eclipse-ee4j/grizzly
        APP_VERSION: e5c322debf631342d8eea888abf898884bfa98a6
      context: ./images/origins/eclipse_grizzly
    x-props:
      role: origin
  eclipse_jetty:
    build:
      args:
        APP_BRANCH: jetty-12.1.x
        APP_REPO: https://github.com/eclipse/jetty.project
        APP_VERSION: 18cf857d55f4eb048039172b0d09c5de0fbf8c4b
      context: ./images/origins/eclipse_jetty
    x-props:
      role: origin
  envoy:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/envoyproxy/envoy
        APP_VERSION: 8492f41012d334a88d321972226af5d33747107c
        BAZELISK_TAG: v1.29.0
        CONFIG_FILE: envoy.yaml
      context: ./images/transducers/envoy
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  fasthttp:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/valyala/fasthttp
        APP_VERSION: bf00c3e2dfbe9b8e674968f54492a5ab996d35e3
      context: ./images/origins/fasthttp
    x-props:
      role: origin
  go_stdlib:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/golang/go
        APP_SOURCE: app.go
        APP_VERSION: 9da73fb7025cd64b71608241517d6cb17735d854
        GO_BOOTSTRAP_VERSION: 1.25.0
        START_SCRIPT: start.sh
      context: ./images/origins/go_stdlib
    x-props:
      requires-tls: true
      role: origin
  go_stdlib_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/golang/go
        APP_SOURCE: proxy.go
        APP_VERSION: 9da73fb7025cd64b71608241517d6cb17735d854
        GO_BOOTSTRAP_VERSION: 1.25.0
        START_SCRIPT: start_proxy.sh
      context: ./images/origins/go_stdlib
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  gunicorn:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/benoitc/gunicorn
        APP_VERSION: 9bc5891b4b06f25a8ce0e707053dcb2fb9bf638c
      context: ./images/origins/gunicorn
    x-props:
      role: origin
  h2o:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/h2o/h2o.git
        APP_VERSION: e27c3e6d8cc04b8b7c3dea35dbd00e41d5ad734c
        CONFIG_FILE: h2o.conf
        PARSER_BRANCH: master
        PARSER_REPO: https://github.com/h2o/picohttpparser
        PARSER_VERSION: f4d94b48b31e0abae029ebeafcfd9ca0680ede58
        START_SCRIPT: start.sh
      context: ./images/origins/h2o
    x-props:
      requires-tls: true
      role: origin
  h2o_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/h2o/h2o.git
        APP_VERSION: e27c3e6d8cc04b8b7c3dea35dbd00e41d5ad734c
        CONFIG_FILE: h2o-proxy.conf
        PARSER_BRANCH: master
        PARSER_REPO: https://github.com/h2o/picohttpparser
        PARSER_VERSION: f4d94b48b31e0abae029ebeafcfd9ca0680ede58
        START_SCRIPT: start_proxy.sh
      context: ./images/origins/h2o
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  haproxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: 32fc35ef0929b18a3a322f2886bba856b73cc4ee
        CONFIG_FILE: haproxy.conf
        START_SCRIPT: start.sh
      context: ./images/origins/haproxy
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  haproxy_fcgi:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: 32fc35ef0929b18a3a322f2886bba856b73cc4ee
        CONFIG_FILE: haproxy-fcgi.conf
        START_SCRIPT: start_fcgi.sh
      context: ./images/origins/haproxy
    x-props:
      role: origin
  hyper:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/hyperium/hyper
        APP_VERSION: cad38b7ba8e485e1200685e472fb4ffe54517840
        HYPER_UTIL_BRANCH: master
        HYPER_UTIL_REPO: https://github.com/hyperium/hyper-util
        HYPER_UTIL_VERSION: 911d0f256342fa6740721104418c6102dc7d1d0b
      context: ./images/origins/hyper
    x-props:
      role: origin
  hypercorn:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/pgjones/hypercorn
        APP_VERSION: 0e2311f1ad2ae587aaa590f3824f59aa5dc0e770
      context: ./images/origins/hypercorn
    x-props:
      requires-tls: true
      role: origin
  ktor:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/ktorio/ktor
        APP_VERSION: eac67e82d3d60bedbbf7aa0ed72acc1426cb18e7
        KOTLIN_COMPILER_ZIP_URL: https://github.com/JetBrains/kotlin/releases/download/v2.3.20/kotlin-compiler-2.3.20.zip
      context: ./images/origins/ktor
    x-props:
      role: origin
  libevent:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/libevent/libevent
        APP_VERSION: 3912dae14d4642ce4d209fe258b3bc874c039267
      context: ./images/origins/libevent
    x-props:
      role: origin
  libmicrohttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://git.gnunet.org/libmicrohttpd.git
        APP_VERSION: d2375954a17f8a2aca323691d55ce7aa3d0336b9
      context: ./images/origins/libmicrohttpd
    x-props:
      role: origin
  libsoup:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://gitlab.gnome.org/GNOME/libsoup.git
        APP_VERSION: 8478182216288f288e4e4e9618b6e1b07b8b974f
      context: ./images/origins/libsoup
    x-props:
      role: origin
  lighttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/lighttpd/lighttpd1.4
        APP_VERSION: 3651e9be9ee7d9afd04f9e7c956a40f3633656e1
        CONFIG_FILE: server.conf
        START_SCRIPT: start.sh
      context: ./images/origins/lighttpd
    x-props:
      role: origin
  lighttpd_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/lighttpd/lighttpd1.4
        APP_VERSION: 3651e9be9ee7d9afd04f9e7c956a40f3633656e1
        CONFIG_FILE: proxy.conf
        START_SCRIPT: start_proxy.sh
      context: ./images/origins/lighttpd
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  mongoose:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/cesanta/mongoose
        APP_VERSION: 911fad4be98118b8653c2ddf13c094fcace6625f
        SERVER_SOURCE: main.c
      context: ./images/origins/mongoose
    x-props:
      role: origin
  netty:
    build:
      args:
        APP_BRANCH: 4.2
        APP_REPO: https://github.com/netty/netty
        APP_VERSION: b022b4786f2b8258ea75d5b613957a01f2246c5b
      context: ./images/origins/netty
    x-props:
      role: origin
  nghttpx:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nghttp2/nghttp2
        APP_VERSION: 8edad4ec4a708f9ff003c16033d0d0d64fd3573c
      context: ./images/transducers/nghttpx
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  nginx:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nginx/nginx
        APP_VERSION: d44205284fa41662da803b796d6056fc1e59b1f3
        CONFIG_FILE: nginx.conf
        START_SCRIPT: start.sh
      context: ./images/origins/nginx
    x-props:
      role: origin
  nginx_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nginx/nginx
        APP_VERSION: d44205284fa41662da803b796d6056fc1e59b1f3
        CONFIG_FILE: nginx-proxy.conf
        START_SCRIPT: start_proxy.sh
      context: ./images/origins/nginx
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  node_stdlib:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/nodejs/node
        APP_VERSION: b9203ee79fbf6d8800e968ce095c8431619779f4
        SCRIPT: app.js
      context: ./images/origins/node_stdlib
    x-props:
      requires-tls: true
      role: origin
  openbsd_httpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/kenballus/obhttpd-linux
        APP_VERSION: 13177feda2e869a13b07221385e850d07b3f16b1
        OPENBSD_SRC_BRANCH: master
        OPENBSD_SRC_REPO: https://github.com/openbsd/src
        OPENBSD_SRC_VERSION: c7a005c9178b61ab787ad0117fb2b81da67a380d
      context: ./images/origins/openbsd_httpd
    x-props:
      role: origin
  openlitespeed:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/litespeedtech/openlitespeed
        APP_VERSION: 28f7da33745c8921a00994211059884096e95ba5
        CONFIG_FILE: server_config.conf
        START_SCRIPT: start.sh
        VHOST_CONFIG_FILE: server_vhost.conf
      context: ./images/origins/openlitespeed
    x-props:
      role: origin
  openlitespeed_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/litespeedtech/openlitespeed
        APP_VERSION: 28f7da33745c8921a00994211059884096e95ba5
        CONFIG_FILE: proxy_config.conf
        START_SCRIPT: start_proxy.sh
        VHOST_CONFIG_FILE: proxy_vhost.conf
      context: ./images/origins/openlitespeed
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  openwrt_uhttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://git.openwrt.org/project/uhttpd.git
        APP_VERSION: 1b624f8f814ed568608d756512892416e0431d77
        LIBUBOX_BRANCH: master
        LIBUBOX_REPO: https://git.openwrt.org/project/libubox.git
        LIBUBOX_VERSION: 1fe93d2fefb213ec987763e7e94ce5eaa757bfc3
        LIBUBUS_BRANCH: master
        LIBUBUS_REPO: https://git.openwrt.org/project/ubus.git
        LIBUBUS_VERSION: 795b32bb96b611493f423666236e9c1e49e0736c
        UCODE_BRANCH: master
        UCODE_REPO: https://github.com/jow-/ucode
        UCODE_VERSION: 0beaa9dc244f16c52c0a7dc3f180cca0539124cd
        USTREAM_SSL_BRANCH: master
        USTREAM_SSL_REPO: https://git.openwrt.org/project/ustream-ssl.git
        USTREAM_SSL_VERSION: 99f1c0db5a729f615bc5114b3b52fd8ac8083f34
      context: ./images/origins/openwrt_uhttpd
    x-props:
      role: origin
  pound:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/graygnuorg/pound
        APP_VERSION: ccf1d1c86d38669c0687d2dc0cd9091df8c1bb14
      context: ./images/transducers/pound
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  protocol_http1:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/socketry/protocol-http1
        APP_VERSION: 6e4af8c818f7af8f0d77e0dc60e3c4f85f64df59
      context: ./images/origins/protocol_http1
    x-props:
      role: origin
  reactphp:
    build:
      args:
        APP_BRANCH: 3.x
        APP_REPO: https://github.com/reactphp/http
        APP_VERSION: bb151a7cdf9e7b49caac9030add52c6427ebc6d2
      context: ./images/origins/reactphp
    x-props:
      role: origin
  puma:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/puma/puma
        APP_VERSION: ec6db67a63e846d4b82109bffa18d4dc528b129a
      context: ./images/origins/puma
    x-props:
      role: origin
  squid:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/squid-cache/squid
        APP_VERSION: ec328cf16eff35be1a2d938fedc8a1b764ddff10
      context: ./images/transducers/squid
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  thin:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/macournoyer/thin
        APP_VERSION: e7886a9bca2742586da74e06fffdd2093cc3a397
      context: ./images/origins/thin
    x-props:
      role: origin
  tornado:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/tornadoweb/tornado
        APP_VERSION: ecc40ae19fd30489435635f54841ca45613f59fc
      context: ./images/origins/tornado
    x-props:
      role: origin
  twisted:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/twisted/twisted
        APP_VERSION: 9d1e48d8fba1ba61857f59591d949f9a456fcba9
      context: ./images/origins/twisted
    x-props:
      role: origin
  undertow:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/undertow-io/undertow
        APP_VERSION: a21c6d8ea421e10bcc72392204533be6029e52ea
      context: ./images/origins/undertow
    x-props:
      role: origin
  uvicorn:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/Kludex/uvicorn
        APP_VERSION: 57b3991d5f6f8e2f750378be5eada7c4fedd90f9
      context: ./images/origins/uvicorn
    x-props:
      role: origin
  uwsgi:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/unbit/uwsgi
        APP_VERSION: 8d116f7ea2b098c11ce54d0b3a561c54dcd11929
      context: ./images/origins/uwsgi
    x-props:
      role: origin
  vinyl:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://code.vinyl-cache.org/vinyl-cache/vinyl-cache.git
        APP_VERSION: 25761f8505817ac50df994270bfe75b60073e33e
      context: ./images/transducers/vinyl
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
  waitress:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/Pylons/waitress
        APP_VERSION: 4a378915f6fef264c6aaf03f059bd992287ba8ba
      context: ./images/origins/waitress
    x-props:
      role: origin
  webrick:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/ruby/webrick
        APP_VERSION: dd6a0a8a7ba8ae170114393da5ae5871b08393ab
      context: ./images/origins/webrick
    x-props:
      role: origin
  yahns:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://yhbt.net/yahns.git
        APP_VERSION: 6a1ce36be271630f6b97bc415f4961605a562ef0
        CONFIG_FILE: server.ru
        PARSER_BRANCH: master
        PARSER_REPO: https://yhbt.net/unicorn.git
        PARSER_VERSION: e9862718a7e98d3cbec74fc92ffc17a1023e18da
        START_SCRIPT: start.sh
      context: ./images/origins/yahns
    x-props:
      role: origin
  yahns_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://yhbt.net/yahns.git
        APP_VERSION: 6a1ce36be271630f6b97bc415f4961605a562ef0
        CONFIG_FILE: proxy.ru
        PARSER_BRANCH: master
        PARSER_REPO: https://yhbt.net/unicorn.git
        PARSER_VERSION: e9862718a7e98d3cbec74fc92ffc17a1023e18da
        START_SCRIPT: start_proxy.sh
      context: ./images/origins/yahns
    volumes:
    - ./tools:/tools
    x-props:
      role: transducer
